### ISSUE TITLE
myVi website clone(Frontend)

### ISSUE THREAD

**Issue by G0V1NDK** [crazycodigo/Coding-Basics-HacktoberFest2022#104]
I want to contribute here by adding the Vodafone-Idea website clone project(HTML, CSS(Bootstrap), js)

**Comment by Jayanti2919** [comment]
Go ahead

**Comment by G0V1NDK** [comment]
I did "Compare & Pull Request" -> "Create a Pull Request" after pushing the code.
Is it fine? @Jayanti2919
