### ISSUE TITLE
N Queen algorithm -> Coding-Basics-HacktoberFest2022/Algoritms/

### ISSUE THREAD

**Issue by vryan-06** [crazycodigo/Coding-Basics-HacktoberFest2022#135]
I wish to add the N Queen problem in the Algorithms folder. I will be writing the algorithm in Java.

**Comment by vryan-06** [comment]
Kindly assign me this issue as a part of Hacktoberfest 2022. Thank you!

**Comment by Jayanti2919** [comment]
Go ahead

**Comment by Sandyy07** [comment]
Kindly Please assign me this issue.

**Comment by anjaliisonii** [comment]
I also want to contribute in this algorithm.
kindly assign to me.
