### ISSUE TITLE
EXCLUDED REPOSITORY

### ISSUE THREAD

**Issue by akash-rajak** [crazycodigo/Coding-Basics-HacktoberFest2022#182]
This Respository is excluded from Hacktoberfest 2022.

**Comment by hrshbrdhnn** [comment]
Are you sure that this repository is excluded?

**Comment by akash-rajak** [comment]
yes
you can see here

![image](https://user-images.githubusercontent.com/57003737/196016626-3b12f170-7e02-4b51-ad1a-36e1ba5557ad.png)

**Comment by hrshbrdhnn** [comment]
Thank you for letting me know.
