### ISSUE TITLE
Can I make a Rock Paper Scissors game using HTML,CSS and JS?

### ISSUE THREAD

**Issue by bloodmonk7** [crazycodigo/Coding-Basics-HacktoberFest2022#21]
I would like to make a interactive game against the computer using JS. It will take a day or two to complete the game. I will wait if you think this is worth it, then please assign it to me.

**Comment by Jayanti2919** [comment]
Sure, go ahead! @bloodmonk7

**Comment by Jayanti2919** [comment]
This issue has been resolved in PR#27
