### ISSUE TITLE
Reverse Integer Medium LeetCode Problem

### ISSUE THREAD

**Issue by Jayanti2919** [crazycodigo/Coding-Basics-HacktoberFest2022#4]
Provide solution to this problem: [problem](https://leetcode.com/problems/reverse-integer/). 

Comment to get assigned. Do include screenshots of the solution being accepted in your PR.

**Comment by NyanCyanide** [comment]
Can I work on this?

**Comment by ashishpetwal** [comment]
@Jayanti2919 I would like to work on this issue and got the right answer

**Comment by Jayanti2919** [comment]
You can work on it. Please attach screenshot of passed test cases in PR description.

**Comment by ashishpetwal** [comment]
Ok I will

**Comment by Jayanti2919** [comment]
This issue has been resolved
