### ISSUE TITLE
Queue Data Structure

### ISSUE THREAD

**Issue by grraghav120** [crazycodigo/Coding-Basics-HacktoberFest2022#42]
Can I add queue DS using Array implementation for understanding the working of queue.

**Comment by Jayanti2919** [comment]
@grraghav120 what language will you be using?

**Comment by grraghav120** [comment]
In C or C++ according to requirement.

**Comment by Jayanti2919** [comment]
Sure.

**Comment by Lasya6** [comment]
I would like to contribute. Please assign this to me
