### ISSUE TITLE
add counter project in JS

### ISSUE THREAD

**Issue by zabihhaqqani** [crazycodigo/Coding-Basics-HacktoberFest2022#45]
- I have a basic counter project that is made using JavaScript.
- I can also explain the process of making it step by step.
- helps in understanding DOM manipulation in JavaScript.

![gif](https://user-images.githubusercontent.com/53895282/193517581-1beb9b94-f99a-4f7b-bc44-05940141b592.gif)

**Comment by Jayanti2919** [comment]
Go ahead!

**Comment by zabihhaqqani** [comment]
Thank you !
