### ISSUE TITLE
Able to create other pull request for different projects ?

### ISSUE THREAD

**Issue by lhpellizzon** [crazycodigo/Coding-Basics-HacktoberFest2022#56]
I just want to know if it is possible to make more than one pull request for different project, after the first pull request is approved.
I have others projects and web components that I would like to share if possible.
Thanks for everything.

**Comment by Jayanti2919** [comment]
Yeah that works. There is no limit to how many PRs you can make/ how many projects you can submit as long as they are all genuine and valid
