### ISSUE TITLE
I will be adding the Rock, Paper and Scissors In python.

### ISSUE THREAD

**Issue by MayankUghade** [crazycodigo/Coding-Basics-HacktoberFest2022#68]
Can I add the rock paper scissors problem in python programe language?
@Jayanti2919 Please assign me under the hacktoberfest - Accepted tag.

**Comment by Jayanti2919** [comment]
You added an empty file

**Comment by MayankUghade** [comment]
hey @Jayanti2919 even I dont have any idea how it happened , can you tell me how to change this ? because I have created a real
game which is fun to play.
